### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by Sq00ky** [smridhgupta/alpha-wpes#3]
see: title
Github isn't really for distribution of pre-compiled software, especially those pyinstaller/py2exe'd + pyarmor'd. Just weird...

**Comment by smridhgupta** [comment]
The code of Alpha-WPES is copyrighted under the Berne Convention, so trying to reverse engineer the code of Alpha-WPES goes **against the law** (FYI). I pyarmor'd it so that masses cannot break and use the code. But if you want to reverse engineer the code and make sure there is no backdoor implementation, **you have my permission** to do so.
